services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:80" # map host 5000 to container 80
    depends_on:
      - db
    environment:
      - ConnectionStrings__DatabaseConnection=Host=db;Port=5432;Database=app;Username=postgres;Password=poplm10@

  frontend:
    build:
      context: ./FE-C
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: poplm10@
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
